export {default as Header} from './Header'
export {default as Footer} from './Footer'
export {default as AddItem} from './AddItem'
export {default as Slide} from './Slide'
export {default as AddSlide} from './AddSlide'
export {default as AddCategory} from './AddCategory'